###create team
Post http://localhost:4000/team/create
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "name" : "آسمانی ها",
    "description" : "wa are so close to GOD",
    "username" : "Angles"
}

###get all teams
GET  http://localhost:4000/team/list
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

###get team by id
GET  http://localhost:4000/team/63109754b506aa79310f4633
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

###get my teams
GET  http://localhost:4000/team/me
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

###remove team by id
DELETE   http://localhost:4000/team/remove/631090ca29142f572fc20233
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

###edit team by id
put   http://localhost:4000/team/edit/630f52dac7531e04454805ac
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "title" : "",
    "text" : "",
    "tags" : ["", ""]
}
