### get user profile
GET  http://localhost:4000/user/profile
Authorization: Bearer {{$dotenv TOKEN}}

### edit user profile
POST http://localhost:4000/user/profile
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "first_name" : "mmd",
    "last_name" : "talebi",
    "skills" : ["programming", "nodejs", "express"]
}

### get user requests
GET  http://localhost:4000/user/requests
Authorization: Bearer {{$dotenv TOKEN}}

### get user requests by status
GET  http://localhost:4000/user/requests/pending
Authorization: Bearer {{$dotenv TOKEN}}

### get chenge status request
get http://localhost:4000/user/change-status-request/63127c6e6fe0c1468ec4b54d/accepted
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json